### ISSUE TITLE
/projects/:project route is broken?

### ISSUE THREAD

**Issue by suren-atoyan** [bestofjs/bestofjs-webui#101]
I see this when I open `https://bestofjs.org/projects/:project`

To reproduce:

1) go to `https://bestofjs.org`
2) open any project

<img width="1029" alt="Screen Shot 2021-01-21 at 20 27 58" src="https://user-images.githubusercontent.com/13118722/105380318-2dfd7f80-5c27-11eb-8942-f3ae62c54afc.png">

**Comment by michaelrambeau** [comment]
Sorry for the trouble, there is a technical problem right now, I'm investigating...

**Comment by michaelrambeau** [comment]
Hello again Suren @suren-atoyan 
It seems data is no more available 🙀 which explains why we have an app that shows `0` projects.
I've just deployed a "hot fix" to show data from yesterday and disable some components.
Could you check if it works?
Thank you in advance.

**Comment by suren-atoyan** [comment]
Sure

**Comment by suren-atoyan** [comment]
@michaelrambeau I've just checked. It's not crashing anymore. As you said some components are missing (I noticed a stars-caledlndar component). Thanks
