### ISSUE TITLE
Dynamic titles for different pages

### ISSUE THREAD

**Issue by BBlackwo** [bestofjs/bestofjs-webui#106]
I realised today that the title is static (`Best of JS`) and doesn't get updated when you change pages.

It would improve SEO and share-ability if the title was changed based on the page you are on. E.g. for a specific project `Yarn | Best of JS`. Or for the hall of fame `JavaScript Hall of Fame | Best of JS`. This is what it looks like when you share a specific tag on Slack:

![Screenshot from 2021-06-11 15-16-59](https://user-images.githubusercontent.com/7598058/121634562-1fc1da00-cac8-11eb-9e15-be187972587a.png)

A first pass could be just use the `h1` of the page as the title, which would improve it a lot.

Ideally other metadata such as the `description` should be updated too.

If I get some time I'll try and implement this :slightly_smiling_face:

**Comment by BBlackwo** [comment]
On a related note, the page titles should probably be `h1` instead of `h2` for better SEO/Accessibility.

**Comment by michaelrambeau** [comment]
Thank you very much Benjamin, your are right the site is not optimized for search engines, one of the problems is that everything in generated in client, it could be nice to generate some pages on the server (the top page for example could be re-generated every day on the server when new data is available).

We need a "social image" too (the image that shows up when you share on social medias), like the nice one we did for the _Rising Stars_.

About the heading, in my mind "Best of JS" (the logo) was the top level title but it's just a logo so yes, let's change the HTML tags to start  the content of the page with a `<h1>` tag 👍 .

**Comment by BBlackwo** [comment]
Yeah that would be great to do more server side rendering. That would be a big SEO improvement I imagine. Maybe 

A social image would be a nice improvement.

Changing to a `<h1>` sounds good :slightly_smiling_face:
