### ISSUE TITLE
Markdown images have a black background

### ISSUE THREAD

**Issue by davidcetinkaya** [bestofjs/bestofjs-webui#127]
Hi @michaelrambeau!

I noticed that all images inside a markdown wrapper have a **black background**. Take a look at this example:

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/11529148/152703082-c039a8d6-5643-4083-9204-23a6b3dbb40d.png">

This only happens when **dark mode** is activated. It looks a bit weird. Is this intentional or should it be removed? 

Best,
David

**Comment by michaelrambeau** [comment]
Hello David @davidcetinkaya 
It's good to see you here 😄 
It's not intentional, I'm going to fix very soon it because it looks bad for a lot of projects actually!
Thank you very much, stay tuned!

**Comment by michaelrambeau** [comment]
OK David @davidcetinkaya  I've made a PR and there is a preview URL to check the result:
https://bestofjs-git-fix-logos-inside-markdown-bestofjs.vercel.app/

Could I ask you to have a look? (if possible check both light and dark modes)

Note: the scope is a bit larger as I found as other problem mentioned in the PR. Thank you in advance!

**Comment by davidcetinkaya** [comment]
@michaelrambeau that was fast 🙂! I’ve browsed the preview website for a while and it seems to be working as expected. Good job 👍🏻.

I’m not familiar with all places that use markdown wrappers but it seems like it’s mostly used when displaying the repository README’s.

Best,
David

**Comment by michaelrambeau** [comment]
It was fast because you are a premium user with dedicated support 😆 
We format markdown content to look like GitHub (but with our own "branding" colors) only in the README section.
I will release everything very soon.
Thank you again because it was a really annoying problem.

**Comment by davidcetinkaya** [comment]
Haha thanks @michaelrambeau 😁. All right then! Let me know when you’ve published the changes and I will confirm if it works as expected.

**Comment by michaelrambeau** [comment]
It's live David @davidcetinkaya 🎉 
Please check your wonderful project's page: https://bestofjs.org/projects/embla-carousel

And thank you for the good vibe you provide 😄 !

**Comment by davidcetinkaya** [comment]
Thanks for the swift response @michaelrambeau. It looks great now 😃. Good job!
