### ISSUE TITLE
External links to repository not working

### ISSUE THREAD

**Issue by ruhag** [bestofjs/bestofjs-webui#129]
The link of the anchor tag in the github info page is in the "url" attribute instead of "href".
From the chakra-ui Link component for externallinks the href prop should be set.

**Comment by michaelrambeau** [comment]
Hello @ruhag thank you much, it was a bug indeed, related to changes released yesterday #127 

I've just released a fix: https://github.com/bestofjs/bestofjs-webui/commit/88a8a453cf2048a5bfccffb50b9b42a518e356bc

Could you check again?
