### ISSUE TITLE
A library to hide emails and phone numbers from bots

### ISSUE THREAD

**Issue by ErikGIovani** [bestofjs/bestofjs-webui#134]
https://github.com/ErikGIovani/hidden-from-bots
https://www.npmjs.com/package/hidden-from-bots

**Comment by michaelrambeau** [comment]
Hello Erik, thank you for the idea.
It seems the email address you want to hide is available in the JavaScript file loaded by the browser.
Since some bots can run JavaScript, I wonder if a solution like https://jackchilds.tech/posts/reducing_spam_from_mailto_links would be more robust?

**Comment by ErikGIovani** [comment]
Most of the bots look for the mailto attribute in the dom and hidden from bots does not show the email in the dom, I did tests with various web scraping, for version 1.1.0 I am going to add base 64 encryption and obfuscation systems but for at the moment i am working for the next version to be more robust with advanced web scraping
