### ISSUE TITLE
Monthly rankings for September is broken

### ISSUE THREAD

**Issue by sohrabtaee** [bestofjs/bestofjs-webui#157]
Unable to load the rankings:
https://bestofjs.org/rankings/monthly/2022/9

**Comment by michaelrambeau** [comment]
Hello @sohrabtaee 
Thank you very much for the report.
It was a bug about the data displayed for the current month: the "next" button should be disabled and the "previous" button should let users go to July... but it was the opposite!

About data for September, there will be available at the very end of the month.

Could you check again?

Fixed here: https://github.com/bestofjs/bestofjs-rankings/commit/21b74177bcb28546ffe73eb2265853afd15d6255

![image](https://user-images.githubusercontent.com/5546996/192396377-530c1f21-77f4-4908-9516-d769b54eab0f.png)
