### ISSUE TITLE
Some links show infinite loading

### ISSUE THREAD

**Issue by klaseca** [bestofjs/bestofjs-webui#165]
Example:
$mol - https://bestofjs.org/projects/dollarmol
re:dom -https://bestofjs.org/projects/re:dom

**Comment by michaelrambeau** [comment]
Hello Maxim @klaseca 
Thank you very much for the report!
There was something wrong with data and project's page URL were not correct.
Could you check again?

- https://bestofjs.org/projects/$mol
- https://bestofjs.org/projects/re-dom

**Comment by klaseca** [comment]
Now it works, thanks
