### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by mlfcnt** [bestofjs/bestofjs-webui#168]
The page displays "Login with Github..."

The url changes to : https://bestofjs.org/auth0.html#error=invalid_request&error_description=The%20client_id%20and%2For%20client_secret%20passed%20are%20incorrect.

**Comment by michaelrambeau** [comment]
Hello @mlfcnt thank you for the report!

I have just fixed the setup, could you try again?

**Comment by mlfcnt** [comment]
@michaelrambeau  It worked. Thank you :)
