### ISSUE TITLE
CORS failed, site unavailable

### ISSUE THREAD

**Issue by Maximization** [bestofjs/bestofjs-webui#169]
Hi @michaelrambeau , amazing project!

Wanted to let you know the site is unavailable for me at the moment.

![unavailable](https://user-images.githubusercontent.com/9811142/233521336-5f77e36e-6778-44a9-806f-3c22b544e666.png)

Seems to be a CORS issue with the project.json file.

![network](https://user-images.githubusercontent.com/9811142/233521371-4d634786-f2b8-49e1-bafd-38ce955fac9f.png)

![console](https://user-images.githubusercontent.com/9811142/233521376-f860b9f0-5ffe-4f27-9c17-6228b5c6c03a.png)

Let me know if you need more info.

**Comment by Maximization** [comment]
Seems to be working now 👍. Not sure what fixed it.

**Comment by michaelrambeau** [comment]
Hello @Maximization thank you very much for the report!

There was no change from my side yesterday, maybe something changed from Vercel's side and the timing was unfortunate.

I'm aware that I should get rid of this call to an external domain to avoid potential issues, I'm working on a new architecture.
