### ISSUE TITLE
RSS Feed feature

### ISSUE THREAD

**Issue by tomothumb** [bestofjs/bestofjs-webui#40]
Hi, I request add a feature about RSS Feed.

I always using Feedly for checking trend news.
If this site output several RSS (new repos/ranking/trend feed etc) weekly, it will be awesome!

thanks.

**Comment by michaelrambeau** [comment]
Hello @tomothumb ,
Thank you for the suggestion!

First, since the pages are automatically built every day, I think we could implement a **daily** RSS feed about the overall rankings, do you think it would be useful ?

**Comment by tomothumb** [comment]
umm,
Almost of days, feed shows rankings same as yesterday's one. isn't it?
It seems that a daily feed with ranking is too enough information in my case.
What do you think?

I only want to check the trend actually, like this page.
http://bestof.js.org/projects/trending/this-week

I have no idea what is the best one.

**Comment by michaelrambeau** [comment]
Hello @tomothumb 

I am doing **tests** right now, trying to create a "Weekly trends" RSS feed.

So I created this RSS feed:

http://bestofjs.surge.sh/rss/weekly-trends.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>Best of JavaScript - Weekly trends</title>
    <link>http://bestof.js.org/projects/trending/this-week</link>
    <pubDate>Sat Jun 17 2017 22:11:58 GMT+0900 (JST)</pubDate>
    <lastBuildDate>Sat Jun 17 2017 22:11:58 GMT+0900 (JST)</lastBuildDate>
    <item>
      <title>gun [+164 stars this week]</title>
      <author>amark</author>
      <description>A realtime, decentralized, offline-first, graph database engine.</description>
      <link>http://gun.js.org/</link>
      <pubDate>2017-06-15T21:22:13.000Z</pubDate>
      <image>https://avatars.githubusercontent.com/u/433412?v=3&amp;s=200</image>
    </item>
    <item>
      <title>Feather [+135 stars this week]</title>
      <author>colebemis</author>
      <description>Simply beautiful open source icons</description>
      <link>https://feathericons.com</link>
      <pubDate>2017-06-14T22:33:43.000Z</pubDate>
      <image>https://avatars.githubusercontent.com/u/4608155?v=3&amp;s=200</image>
    </item>
```

Then, I registered to feedly.com and I subscribed to the feed, pasting the XML url.

![image](https://user-images.githubusercontent.com/5546996/27256442-a91bdc82-53ef-11e7-8caa-afe05df745fc.png)

But I don't understand the result: https://feedly.com/i/subscription/feed/http://bestofjs.surge.sh/rss/weekly-trends.xml

For example `Prettier` project is number 1 but it's on the XML feed.

Do you understand what's wrong?
Can you do some tests too?
Do you use feedly.com, or something else?

Thank you for your help!

**Comment by tomothumb** [comment]
Great Job!
I subscribed!

I think Feedly show 5 feeds ordered by <pubDate> of each feed. Don't you think so?

**Comment by soluml** [comment]
Hey guys!

I too love RSS feeds and use a custom homepage via Netvibes to get most of my news.  I added the RSS feed linked to from the site, but it hasn't been updated since June 29th.  Is it still working?

https://bestof.js.org/rss/weekly-trends.xml

**Comment by michaelrambeau** [comment]
Hello @soluml ,
Thank you for your comment, I'm sorry but the weekly RSS feature was put on hold but I'm going to work on it to deliver as soon as possible since there are at least 2 people waiting for it!

**Comment by soluml** [comment]
Yea it's looking good, Netvibes is able to pull it in just fine now.  Thanks for the quick turnaround!

**Comment by michaelrambeau** [comment]
@soluml Thank you for having checked, any feedback about the application is always welcome.

I will confirm next Monday that the feed is correctly updated automatically, stay tuned!

**Comment by michaelrambeau** [comment]
@soluml FYI I have just added a link named "Weekly feed" to the bottom of the pages.
Let me know if if it's OK.

![image](https://user-images.githubusercontent.com/5546996/31581126-dcead336-b19d-11e7-84d0-78908faf2a1a.png)

Stay tuned, we will see in less than 24 hours if the automatic weekly update works 😄 ...

**Comment by michaelrambeau** [comment]
Hello Benjamin @soluml,
Thank you for your patience.
As expected, the weekly feed has been updated automatically this morning, could you check if it's OK?

@tomothumb Sorry it took me a lot of time to time to implement the feature!

**Comment by tomothumb** [comment]
@michaelrambeau 
Awesome and thank you update it!
Very useful. I continue to subscribe.

I have a question.
What is difference between"2d" and "5d" on this screenshot?
Is this day generated date of feed?
I don't know why only 2feeds generated 2days ago.
I will report how does it updated next week.

![image](https://user-images.githubusercontent.com/1335922/31698296-caefc1a8-b3f7-11e7-8411-04666faeb2ea.png)

**Comment by michaelrambeau** [comment]
Hello @tomothumb ,
`* d` is the the number of days between the last commit, **at the time of the feed publication**, and today.
It's a bit difficult to explain because it seems Feedly displays on the same page results from this week and results from the previous week.

For example:

* `deeplearn.js` project was in the feed last week but not this week. `5d` means 5 days between the last commit when the feed was published and today.
* `React` was on both feeds, but the your screenshot displays results from the previous week.

**Comment by michaelrambeau** [comment]
Hello @tomothumb and @soluml 
Before closing the issue, can we consider that the _RSS weekly feed_ feature is OK?
Is there anything you want me to update in the XML file that is generated every week?
https://bestof.js.org/rss/weekly-trends.xml
Thank you!

**Comment by soluml** [comment]
It's working for me, feel free to close.

**Comment by tomothumb** [comment]
This screenshot is newest one.
It works properly weekly. 
![image](https://user-images.githubusercontent.com/1335922/32217175-87aef4fe-be6a-11e7-84be-8feb7c30f0c1.png)

Please close it.

**Comment by michaelrambeau** [comment]
Hello @tomothumb @soluml 

I updated the RSS feed URL: http://weekly.bestofjs.org/rss/trends.xml

The feed is now generated from the weekly newsletter website: http://weekly.bestofjs.org/

Could please update your RSS readers and let me know if it works?

Thank you!

**Comment by soluml** [comment]
Working for me.

**Comment by tomothumb** [comment]
great!

**Comment by michaelrambeau** [comment]
Thank you very much @soluml @tomothumb
