### ISSUE TITLE
Add aggregated data about license? 

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/bestofjs-webui#53]
Here is the feedback I got from Martin @martinheidegger in 2017 September:

> The aggregations are really important, ie. If all libraries are MIT

> Dependencies and subdependencies
> And rather than see the license of all a combination of licenses:: i.e. 95xMIT, 3xBSD

> But I feel like there is some aggregation information that could be REALLY valuable, is not available and could be fairly easily done.
> i.e. If there is one dependency in your tree of a different license than others: that is a major red flag. Particularly if the license is "Unlicensed"

**Comment by michaelrambeau** [comment]
We could use a package called `legally` to get data about all licences involved in a dependency tree:

https://github.com/franciscop/legally

Introduction post: https://hackernoon.com/licenses-for-npm-packages-b2036b4bb6a

Example of response for `Express` project:

```
   ┌────────────────────────────────────────────────────────────────────────┐
   │                                                                        │
   │                             Licenses (48)                              │
   │                                                                        │
   ├──────────────────────────────────────────┬──────────────┬──────────────┤
   │ License                                  │ Number       │ %            │
   ├──────────────────────────────────────────┼──────────────┼──────────────┤
   │ MIT                                      │ 44           │ 91           │
   │ ISC                                      │ 3            │ 6            │
   │ BSD 3 Clause                             │ 1            │ 2            │
   └──────────────────────────────────────────┴──────────────┴──────────────┘

```

@martinheidegger what if BestOfJS gathered these numbers for every project's page, would it be useful?

**Comment by martinheidegger** [comment]
very useful!

**Comment by michaelrambeau** [comment]
An other project related to licenses: https://fossa.io/

> Dependency tracking, license compliance and attribution notices on autopilot 

> Compliance for modern developers

> Continuously scan and comply with open source licenses without slowing down development

**Comment by michaelrambeau** [comment]
I contacted Franciso Presencia, the author of the `legally` project, to be able to integrate `legally` API from _Best of JavaScript_.

Issue: https://github.com/franciscop/legally/issues/19

We could create by ourselves an online node.js service that would call `legally` to fetch license data about any package, calling something like `https://bestofjs-fetch-license.now.sh/express`.

In the UI, the project details page would display a button "Fetch License data" that would call the end-point and display the result in a table.

**Comment by martinheidegger** [comment]
I looked at it and it definitely works and is a good start at this. But why is the lookup so slow? It would be so awesome if it could be readily available.

**Comment by michaelrambeau** [comment]
@martinheidegger Thank you for having checked!

It's slow because it uses under the hood a tool called `legally` that runs `npm install` to check a package and *all* its dependencies. In the beginning, I asked Francisco, the creator of `legally` why it does not just make HTTP requests to gather license data, it seems that the main argument was to avoid having to mimic how NPM resolves the dependencies.

To try to mitigate this issue, results are cached (for 24 hours for now) in a database.

Maybe we could be more "proactive" and automatically fill the cache with the most popular projects, so that the end-users don't suffer too much...

**Comment by michaelrambeau** [comment]
We are are working on a system that periodically fills a persisted cache with the results for the most popular projects... be patient @martinheidegger !

Meawhile, some numbers about the response time for some of the biggest packages:

Name | Dependencies | Duration
--- | --- | ---
rxdb | 737 | 46s
@vue/cli | 641 | 55s
react-native | 597 | 27s
next | 599 | 25s
storybook | 400 | 19s
webpack | 286 | 11s
@nestjs/core | 80 | 7.8s

**Comment by michaelrambeau** [comment]
## Release

We have pushed the trigger and released this new feature!

From the back-end end side, we have implemented a cache, updated periodically using scheduled jobs on the CI server.

As much as possible, the end-user will access license data from the cache (instead of triggering the scanning process).

From the front-side, we made small adjustments:

* Add a red badge if a license is "unlicensed"
* Display when the package has been scanned
* Ask users for feedback, linking to this issue.

![image](https://user-images.githubusercontent.com/5546996/46257810-3633cd00-c4fb-11e8-955d-aedefe035178.png)

Feel free to add comments to this issue!
