### ISSUE TITLE
Include more projects in the `Node.js framework` category

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/bestofjs-webui#58]
## Discussion with Mark Nadal

We had an interesting discussion with @amark, from [Gun project](http://gun.js.org/) about the scope of the `Node.js frameworks` tag.

This is what Mark replied when I said that the category was limited to libraries that can be used to build REST APIs:

> If you feel like NodeJS Framework should stay REST-only then that is your call and I respect that, it just doesn't seem descriptive. I (and if I do a quick google) instinctively think of things like, yes Express, but also Meteor, Parse, Derby, Connect, Flatiron, SocketCluster, etc., just some of my observations:

 > *  Sails and Feathers are listed (even Nest also does it), yet have realtime/websocket abilities, but Meteor, etc. are not.
Perhaps because Meteor is frontend as well? Yet:
> * Flatiron, After.js, etc. are listed.

> My definition (which you don't need to use) is a "NodeJS Framework is a tool that abstracts client-server interactions for the developer, so they can focus on their own API and routes rather than handling the network layer itself."

> If this is true, a tools that allow for developers to use the following code pattern would qualify:

```js
var fw = require('framework');

fw.start(require('http'));

fw.on('myApp/users', function(data){
  console.log(data);
  if(data.foo){
    return fw.next(data);
  }
  fw.reply(data + 1);
});
```

> The reason why this definition excludes `ws` by itself is because `ws` doesn't provide any framework for handling messages/rooms/routes, in the same way HTTP by itself doesn't do that.

> However tools like Express, SocketCluster, Feathers, Gun, etc. do, their API abstracts the communications/networking and gives an API to the user that lets them declare their application structure. Whether this is REST or Realtime or not doesn't seem relevant, just the key: Does it provide routing and middleware?

> Thanks for letting me share my thoughts, and I appreciate how much work you've already put into this, my core proposal is:

> GUN provides many of the same tooling (routing and middleware) as Feathers, Sails, Nest, it is isomorphic like flatiron but not monolithic like Meteor. I think my proposal applies to including a few other projects beyond just GUN, but doesn't open the floodgates. (Although given that "Full-stack framework" tag only has 6 items listed, I don't think it would be unfair to merge those 6, including Meteor, into "NodeJS Framework" tag which has 30, when React and Vue have their own tags, where Vue has 36 as well.)

This issue sums up the moves related to the choice of extending the scope of the `Node.js frameworks` tag, in the way described by Mark.

**Comment by michaelrambeau** [comment]
## Projects to be tagged under `Node.js framework` tag:

* Gun
* Socket Cluster
* All projects under `Fullstack framework` tag: https://bestof.js.org/tags/fullstack (6 projects)

**Comment by michaelrambeau** [comment]
## Tag page

Now we display the the tag description, to make clear the scope behind every tag.

Screenshot of the new `Node.js framework` page, including the description from Mark @amark:

![image](https://user-images.githubusercontent.com/5546996/35181316-efd8fa16-fe02-11e7-9b77-e3fa6d041581.png)

**Comment by amark** [comment]
@michaelrambeau thank you so much for your open consideration, I'm honored you are considering my thought.

Yes, I was suggesting merging "Fullstack Framework" into "NodeJS Framework" (and thus deleting the former).

I was going to offer a definition for "Isomorphic" but noticed you already did - excellent choice!

**Comment by luckylooke** [comment]
I am also missing totaljs project https://github.com/totaljs/framework, it has more then 3.5k stars on github, so I think it deserve to be mentioned ;)

**Comment by michaelrambeau** [comment]
Hello @luckylooke 
`Totaljs` project is available on _Best of JavaScript_ but it was not one of the 10 trendiest frameworks of the year.
Check here: https://bestof.js.org/tags/nodejs-framework/trending/last-12-months

**Comment by luckylooke** [comment]
@michaelrambeau ah, my mistake, thank you :)

**Comment by bpinel** [comment]
Why is EmberJS not even mentionned ?

**Comment by michaelrambeau** [comment]
@bpinel As explained [here](https://github.com/bestofjs/javascript-risingstars/issues/1#issuecomment-357540537) EmberJS was not mentioned in _Rising Stars 2017_ because it was not "hot" in 2017 but it's part of _Best of JavaScript_.
Check the `UI framework` https://bestof.js.org/tags/framework or just search for `Ember` in the search field.
Let me know if it makes sense, thank you!
