### ISSUE TITLE
Export Bookmarks

### ISSUE THREAD

**Issue by LaneLourcey** [bestofjs/bestofjs-webui#59]
I'd love an export bookmarks feature. Downloading a json, csv, or whatever format would be fine. I'd like the download to include the package name, github/npm link, description, stars/downloads, and tags.

Is this at all possible? I'd web scrape it but there aren't any links on the page.

**Comment by michaelrambeau** [comment]
Hello @LaneLourcey , just to understand your request, it's the project list displayed when clicking on "MY PROJECTS" link you'd like to export?

![image](https://user-images.githubusercontent.com/5546996/35758131-ae617b90-08b5-11e8-994d-ee0bcc10161f.png)

**Comment by michaelrambeau** [comment]
Hello @LaneLourcey , thank you for your almost _quick_ reply 😆 !
Just to understand the context, have you a lot of bookmarked projects? (I can't find your profile among users who logged-in, maybe you use an other GitHub account?)

There is already a JSON file available with all data, updated every day. Why not "filter" those data to keep only the projects you're interested in? 
https://bestofjs-api-v2.firebaseapp.com/projects.json
