### ISSUE TITLE
Add bundle size and package install size data

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/bestofjs-webui#61]
## Part 1: the bundle size

When we search for a package on NPM and we have to choose between several options, the size of the bundle created by modules bundles like Webpack is an important criteria.

It would be nice to add the bundle size to _Best of JavaScript_, using data from https://bundlephobia.com/

Example for Redux: https://bundlephobia.com/result?p=redux@4.0.0

![image](https://user-images.githubusercontent.com/5546996/43033255-18f0ab86-8d02-11e8-8178-346b4ce0d872.png)

## Bundlephobia API

https://bundlephobia.com/api/size?package=redux

```json
{
  "dependencyCount": 2,
  "dependencySizes": [
    {
      "approximateSize": 491,
      "name": "symbol-observable"
    },
    {
      "approximateSize": 570,
      "name": "webpack"
    },
    {
      "approximateSize": 10668,
      "name": "redux"
    }
  ],
  "gzip": 2562,
  "hasJSModule": "es/redux.js",
  "hasJSNext": false,
  "hasSideEffects": false,
  "name": "redux",
  "scoped": false,
  "size": 7091,
  "version": "4.0.0"
}
```

Some packages, like `morris.js` generate the following error:

```json
{
  "error": {
    "code": "EntryPointError",
    "message": "We could not guess a valid entry point for this package. Perhaps the author hasn't specified one in its package.json ?",
    "details": {}
  }
}
```

## How to implement it?

2 options:

* We can generate data every day, like we do with the GitHub API and store results in the database.
* We can add a button "Check bundle size" in the project details page (`/projects/redux` for example) that is going to fetch the results on the fly.

Advantage of the 1st solution: we could display the size of the bundle from the project list pages, so that the user can compare easily the size of the bundles.
But it's heavier to implement.

**Comment by michaelrambeau** [comment]
## Project list screenshot

The most meaningfull number is the gizipped size I think.

If `gzip` data is added to the big `projects.json` file, it could be displayed this way in the NPM section, instead of the dependencies count.

![image](https://user-images.githubusercontent.com/5546996/43227895-08340094-909b-11e8-8ec7-05a1c2e8602b.png)

**Comment by michaelrambeau** [comment]
## Part 2: add data about the install size

The bundle size is useful for front-end development, when we ship libraries to the browser.

For back-end project, what matters is the size of the library on the file system once it's installed.

We could use data provided by https://packagephobia.now.sh website.

> Package Phobia reports the size of an npm package before you install it.

> This is useful for inspecting potential devDependencies without using up precious disk space or waiting minutes for npm install.

Example for Express: https://packagephobia.now.sh/result?p=express

![image](https://user-images.githubusercontent.com/5546996/43989812-18c83e2c-9d8c-11e8-96cb-fda4501b4cd4.png)

> The "publish size" is the size of the source code published to npm.

> This number is easy to detect and is typically very small.

API: https://packagephobia.now.sh/api.json?p=express@4.16.3

```json
{
	"publishSize": 206727,
	"installSize": 1638904
}
```

**Comment by michaelrambeau** [comment]
## Project details page next iteration

Information about the package have been gathered into a new "PACKAGE" card, that shows 4 sections:

* The name on npm, followed by the version number and a link "View on NPM"
* The list of dependencies
* Data about the bundle size (from _Bundle Phobia_)
* Data about the package size (from _Package Phobia_)

![image](https://user-images.githubusercontent.com/5546996/44006821-a4f34934-9ec5-11e8-869f-79eff64e4027.png)

The sections are collapsed by default.

### Bundle size details

![image](https://user-images.githubusercontent.com/5546996/44006862-2c14601a-9ec6-11e8-8740-6c085e5fde87.png)

### Package size details

![image](https://user-images.githubusercontent.com/5546996/44006864-3add9602-9ec6-11e8-8db4-5777bd77057a.png)

**Comment by pactera-admindev-zuoheng** [comment]
Hi @michaelrambeau , these features are wonderful, it could help developers to make decission when they choose libs very much. I have 2 small suggestions for details, please consider whether they are acceptable. Thanks.

1. Size's type.
The size behind of **Bundle Size Data** is `Minified + Gzipped`, I think it's better add `Minified + Gzipped` following the size number, linke `2.56Kb (Minified + Gzipped)` so that users could know the type of size number, the could open the section to check more information if need.

2. Open in a new page.
When we click `Bundle Phobia` and `Package Phobia` links that will open the link in current page, I think it's better that open in a new tab so that users could return back to bestof.js easily and that won't break users to check the details like what you do in dependencies links.

**Comment by michaelrambeau** [comment]
Thank you Angelo for your feedback, please check again, I've just pushed a new version.

![image](https://user-images.githubusercontent.com/5546996/44031939-7c66038c-9f40-11e8-8c2b-50c07cac5751.png)

**Comment by michaelrambeau** [comment]
Adjusting the "PACKAGE" card, moving the link "View on NPM" at the bottom:

![image](https://user-images.githubusercontent.com/5546996/44305629-0e5b3080-a3b7-11e8-9809-94af939490a6.png)
