### ISSUE TITLE
Many feed doesn't have source link.

### ISSUE THREAD

**Issue by tomothumb** [bestofjs/bestofjs-webui#62]
Some feed such as vuejs has a `<link>...</link>` on xml.  
It seems that it depends whether project have their official website or not.  
http://weekly.bestofjs.org/rss/trends.xml

I'm using feedly to see weekly feeds.  
Blank window will opened when I click no <link /> project on feedly.

Is it possible to add github.com link, npm.org link or bestofjs.org link on feed content? 

I think it worked properly before.

**Comment by michaelrambeau** [comment]
Hello @tomothumb thank you for your feedback!

I've just deployed a fix, could you check if it's OK?

https://weekly.bestofjs.org/rss/trends.xml
