### ISSUE TITLE
misspelled repo name: Ldize -> Idlize

### ISSUE THREAD

**Issue by charlescwitte** [bestofjs/bestofjs-webui#65]
misspelled repo name: Ldize -> Idlize
Let me know if there's a better protocol for minor textual issues like this.
Love "Best of JS" site - I check it daily!

**Comment by michaelrambeau** [comment]
Hello @charlescwitte 
Thank you for the feedback, it will be fixed in a few hours when the site is rebuilt.
And thank you for your kind worlds 😄 !

**Comment by michaelrambeau** [comment]
Hello @charlescwitte 
It has been fixed, could you check here: https://bestofjs.org/tags/performance

Thank you again!

**Comment by charlescwitte** [comment]
It looks perfect to me.  Thanks & keep up the great work!
