### ISSUE TITLE
icons failed to render

### ISSUE THREAD

**Issue by dnafication** [bestofjs/bestofjs-webui#66]
Some of the tech icons failed to rener on the following route: https://bestofjs.org/tags/react/trending/today

- nextjs
- Formik
- Docz
- Docusaurus
... may be more

![image](https://user-images.githubusercontent.com/6381587/46990467-2c41d900-d14d-11e8-85f3-2a4c4bedf9b0.png)

Let me know if I can work on it.

**Comment by dnafication** [comment]
In fact, I was able to see the icons on my phone. Tried it again on incognito mode (chrome) on pc, the version is 0.12.0 and some of the images are still broken.

**Comment by michaelrambeau** [comment]
If you see the version is `0.12.0`, it means that it's not the latest version that is served to your computer.
There is something wrong either at Netlify or CloudFare level, I'm not sure, I'm going to investigate more but it seems a bit tricky.
I will call you back as soon as I find a solution or a workaround, thank you again and sorry for the inconvenience.

**Comment by michaelrambeau** [comment]
Hello @dnafication 
Could you try again, reloading the page in the browser?
I've just triggered a new build process on Netlify, from a branch called `production` instead of the `master` branch.
It seems it has solved the problem on my computer.
Thank you in advance!

**Comment by dnafication** [comment]
Hi @michaelrambeau 
Sorry, I totally forgot to reply to you. I have checked it back then and I also felt it was due to cache as the version displayed was 0.12.0.
It looks fine now. I have also attached what I see right now. Also, will close this.

![image](https://user-images.githubusercontent.com/6381587/47395492-a9370900-d772-11e8-9a00-aa105fa30889.png)
