### ISSUE TITLE
'Html & text parsing' category should be 'HTML & text parsing'

### ISSUE THREAD

**Issue by coliff** [bestofjs/bestofjs-webui#67]
RE: https://bestofjs.org/tags/parsing

I think 'Html & text parsing' category should be 'HTML & text parsing'

**Comment by michaelrambeau** [comment]
Thank you Christian @coliff 

It has just been fixed.

![image](https://user-images.githubusercontent.com/5546996/50315017-697f6a00-04f4-11e9-9812-c4f8b1bc42f5.png)
