### ISSUE TITLE
Congratulations on 1k ⭐️!

### ISSUE THREAD

**Issue by davidcetinkaya** [bestofjs/bestofjs-webui#73]
Just wanted to congratulate you on 1k ⭐️, 🥳🎉!

Have a great day and you may close this issue 😊.

**Comment by michaelrambeau** [comment]
Hello David @davidcetinkaya 

Thank you very much, it took time but we passed the 1k milestone, that's something to celebrate, you're right!

There are a lot of things to improve to make the project more useful for the community... and reach the 10k milestone!

**Comment by davidcetinkaya** [comment]
@michaelrambeau Michael you're right, just keep on going 😃⭐️!
Just wanted to stop by and congratulate you. Have a great day and talk to you soon again I hope 👍.
