### ISSUE TITLE
Improve the search engine, multi tag search

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/bestofjs-webui#75]
The search module should be improved, the user should be able to search for projects by selecting one or several tags.

The user should be able to find a list of projects by entering text (the current full-text search) and/or selecting one or several tags.

This new search engine should be included at the top of any page, a bit like [Yarn](https://yarnpkg.com/en/) does.

For the tag filter, we can implement a drop-down menu with autocomplete feature, like this one [React Select](https://react-select.com/components)

The problem: how we combine the 2 features (full-text search and filter by tags)?

#### Option A

Can the same input field be used for the 2 purposes?

it means that when the user starts to type, the matching tags are displayed (waiting for being selected by the user) and a list of projects that match the text is also displayed below (which can be confusing?)

#### Option 2

Or is it better to split the 2 controls?

For example: a textbox on the left to enter any text to trigger the full-text search and the "tags" auto-complete field on the right.

**Comment by michaelrambeau** [comment]
## First iteration

It’s still _Work In Progress_ but I’d like to share a preview of the *next* Best of JavaScript!
https://next--bestofjs.netlify.com/

The main change is a *new search engine* that lets you combine one or several tags with keywords, in the same search box.
Also, when you pick an option (like “show by number of stars since yesterday”) it’s preserved while you navigate.
The design has changed , no more huge sidebar, but it’s still quite raw.
It’s inspired by https://yarnpkg.com/.

#### Screenshots

![image](https://user-images.githubusercontent.com/5546996/65732266-031f1c00-e104-11e9-98f9-d514fadc228d.png)

**Comment by bluebill1049** [comment]
personally I prefer one control (UX point of view), I think this is a great feature for people searching for packages with their need. I am loving it.

A use case for me: I would just go `react` and then `forms`

**Comment by michaelrambeau** [comment]
Thank you very much @bluebill1049 for the feedback.

I will try to improve the search by tag before releasing in production.
Specific tags like "Forms" are often related to more generic tags like "React" or "Vue.js".
For example if you pick `Form`, or `Component Toolkit`, it will be nice to be able to pick easily "React" or "Vue.js", because people often search for libraries related to a given framework.

An other point you could check: we improved the "bookmark" feature for logged-in users.
Maybe you could try to bookmark your 4 projects on _Best of JavaScript_ 😄 

![image](https://user-images.githubusercontent.com/5546996/65833250-2b2b9c80-e309-11e9-804e-49b9de0537ae.png)

**Comment by bluebill1049** [comment]
aha yea I will try that :)

**Comment by devhero** [comment]
The search field is very useful, IMO it's the fastest way to find by tags or by name.
It's a good work and improves a lot the experience.

My UX remarks:
- search field
  - on second spacebar press, just after the suggestions shown, it shouldn't insert the current selected item (almost always the first), it happens too often to accidentally insert a non wanted item
  - when emptied (eg. after deletion of all tags) it's the same state of the homepage, so the page should be the homapage and not a list of ALL projects; there's already the hidden button 'All Projects' to achieve that result
- hamburger button: it's not appealing to use it and should not exists on non-mobile, the submenu has a very short list and a flat horizontal menu should be good enough

My 2 cents for now :-)

**Comment by michaelrambeau** [comment]
Thank you very much for your feedback @devhero!

About the layout, I removed the hamburger button and created a classic menu with. I feel like it's giving too much importance to these 2 menu items but I'm not sure and it's better than before, I think.
The mobile layout is on my todo list (either a basic dropdown menu or a off-canvas sidebar)

![image](https://user-images.githubusercontent.com/5546996/66213109-13ce2400-e6fa-11e9-83cb-3f92a7a1ddae.png)

If the user reset the search query, I did what you said: back to the home page.

About the space key, it seems that the first space key opens the suggestions and the second one selects the focused element (or the first element if nothing is focused) I'm curious to know what would be the behavior you expect?

**Comment by devhero** [comment]
About the space key, my idea is that it should works just at the first click (showing suggestions) and once in that status nothing else.

**Comment by michaelrambeau** [comment]
Hello @devhero 
Thank you very much for your time!

As soon as the drop-down menu opens to show the suggestions, the first element is focused and therefore a space key event means that the element is selected.
To solve the problem, I've inserted a blank element "_Pick a tag_..." that does not trigger any tag selection, it only closes the drop-down menu when it's clicked.
Could you check again?

<img width="942" alt="image" src="https://user-images.githubusercontent.com/5546996/66250100-e4123100-e778-11e9-9b2a-a246a0c2772e.png">

**Comment by michaelrambeau** [comment]
Hello Andrew @ragamufin

I took into account 2 points you mentioned.

#### Point A: backspace key behavior

You can move the cursor just after the tag, before the free text, and press the backspace key, the last tag will be removed without removing the user query.

![image](https://user-images.githubusercontent.com/5546996/66789019-c1c0a600-ef24-11e9-911b-2189b9319351.png)


#### Point B: more flexible queries

You can now search for `react native web` and "React Native for Web" will come back.
Under the hood, if the user enters spaces, it's considered as a place holder for any character, it may have side effects.

Check: `https://next--bestofjs.netlify.com/projects?query=react native web`

![image](https://user-images.githubusercontent.com/5546996/66788785-f4b66a00-ef23-11e9-9e09-53a63b66811e.png)

Thank you again!

**Comment by ragamufin** [comment]
@michaelrambeau wow fast! nice

Yup, it works excellently now. Very smooth. 

I guess the last bullet point I sent is pretty tricky to do huh? As it is now it is perfect so I'd let it be as it is, somehow now without the sidebar it feels spacious and breezy, good work!

**Comment by michaelrambeau** [comment]
@ragamufin Thank you very much for having checked Andrew!
About the third point, I will tell you if I can find a solution, I didn't have time to investigate but I'm keeping that point in mind.

**Comment by michaelrambeau** [comment]
## Latest iteration, including improvement for mobiles

### On desktops

<img width="999" alt="image" src="https://user-images.githubusercontent.com/5546996/67142999-c0370b00-f2a1-11e9-8167-485a690b89a4.png">

### On mobiles

<img width="391" alt="image" src="https://user-images.githubusercontent.com/5546996/67143126-12c4f700-f2a3-11e9-8079-500bd61a9897.png">

**Comment by michaelrambeau** [comment]
## Screenshot for the README.md

![image](https://user-images.githubusercontent.com/5546996/67169301-8f5fee80-f3e5-11e9-837b-0c94606d21c1.png)

**Comment by michaelrambeau** [comment]
Released in v0.19 https://github.com/bestofjs/bestofjs-webui/releases/tag/0.19.0
