### ISSUE TITLE
Provide a badge for project's README

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/bestofjs-webui#79]
As suggested by @coliff we could provide a badge to be included by the projects we track on _Best of JavaScript_.

> I was thinking you could have 'as featured on best of JS' SVG badges or something - and repos could add them to their READMEs and it could generate extra traffic to your site.

It could it be either static content like "Featured on Best of JavaScript", delivered by https://shields.io/ service...

![badge](https://img.shields.io/badge/Featured%20on-Best%20of%20JavaScript-orange)

..or something more advanced, the badge could give information about the project trends, if we provide a specific end-point (see https://shields.io/endpoint).

![badge](https://img.shields.io/badge/Best%20of%20JavaScript-500%20stars%20this%20month-orange)

Alternative: https://badgen.net/

**Comment by michaelrambeau** [comment]
## Some ideas

### Static badges

They open a given tag in Best of JavaScript

[![BestofJS: Hot Project](https://img.shields.io/badge/Best%20of%20JS-Node.js%20framework-orange)](https://bestofjs.org/projects?tags=nodejs-framework)

### Dynamic badges

They show statistics about a given project and open the project's details page

[![BestofJS: Hot Project](https://img.shields.io/badge/Best%20of%20JS-+10%20★%20today-orange)](https://bestofjs.org/projects/dark-mode-switch)

[![BestofJS: Hot Project](https://img.shields.io/badge/Best%20of%20JS-+100%20★%20this%20week-orange)](https://bestofjs.org/projects/dark-mode-switch)

**Comment by michaelrambeau** [comment]
# First iteration

To provide data about the project trends, an end-point has been deployed using Vercel serverless functions

### URL of the badge

The following URL will return an image to be included in the markdown document:

https://img.shields.io/endpoint?url=https://bestofjs-serverless.now.sh/api/project-badge?fullName=reduxjs/redux&since=daily

Parameters:

- `fullName`: project full name on GitHub
- `since`: the period, can be `daily` (default value), `weekly`, `monthly` or `yearly`

Caution: `&` and `/` parameters in the query string of the API end-point should be encoded when calling the badge image URL:

- `/` => `%2F`
- `&` => `%26`

### Markdown snippet

#### Example 1: `reduxjs/redux` project on GitHub, `redux` on _Best of JS_

```md
[![Best of JS](https://img.shields.io/endpoint?url=https://bestofjs-serverless.now.sh/api/project-badge?fullName=reduxjs%2Fredux%26since=daily)](https://bestofjs.org/projects/redux)
```

Result on the screen

[![Best of JS](https://img.shields.io/endpoint?url=https://bestofjs-serverless.now.sh/api/project-badge?fullName=reduxjs%2Fredux%26since=weekly)](https://bestofjs.org/projects/redux)

#### Example 2: `Dark Mode Swich` for my friend @coliff 

[![Best of JS](https://img.shields.io/endpoint?url=https://bestofjs-serverless.now.sh/api/project-badge?fullName=coliff%2Fdark-mode-switch%26since=monthly)](https://bestofjs.org/projects/dark-mode-switch)

**Comment by coliff** [comment]
Great job on these Michael - they look really neat.

Added here now: https://github.com/coliff/dark-mode-switch
