### ISSUE TITLE
i can't sign in. https://bestofjs.org/

### ISSUE THREAD

**Issue by VacantThinker** [bestofjs/bestofjs-webui#80]
- problem

i click sign in button, the website get fresh. the page shows text "github login...". then the website fresh stop. the sign in button still there, nothing get change..

- location

China

- browser

chrome

- system os

windows10

**Comment by michaelrambeau** [comment]
Hello @VacantThinker 
It may be an issue with GitHub login feature.
Are you able to login to GitHub from your location?

**Comment by VacantThinker** [comment]
i can login github. i can post an issue.

**Comment by VacantThinker** [comment]
still can't sign in https://bestofjs.org/. later, i will reinstall my system os windows 10. try it again. it will be cost 30 min...

**Comment by michaelrambeau** [comment]
Hello again @VacantThinker 
Sorry for the inconvenience, you're right, there is a problem, I'm investigating...
Please wait a little more!

**Comment by michaelrambeau** [comment]
@VacantThinker Sorry for the delay, could you try again?

**Comment by VacantThinker** [comment]
i try it again. it's work. chrome ok. edge ok. firefox ok. thank's a lot. next, i will close the issue.
