### ISSUE TITLE
Add a page showing all the tags

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/bestofjs-webui#83]
Goal: add a page showing a list of all available tags.

Before the new layout was introduced (see #75 ), it was possible to see all the tags and navigate through them using the left side bar but it's no more possible.

From a comment by @gamtiq https://github.com/knsv/mermaid/issues/216

> One feature that I miss is a separate page with all tags.
The previous version of Best of JavaScript had a sidebar that listed all available tags.
Now set of available tags is only accessible by drop-down list which sometimes is not convenient (not user-friendly).
I suppose the separate page with all available tags-links (and perhaps some additional data/stats for each tag) would be helpful.

**Comment by michaelrambeau** [comment]
## First iteration

A new page called "All Tags", has been created.
A link "Tags" has been added to the top menu.

By default tags are sorted by the number of projects (starting with `React` tag), but tags can be sorted by alphabetical order too.

@gamtiq Could you check here (this is a temporary URL): https://next--bestofjs.netlify.com/tags

![image](https://user-images.githubusercontent.com/5546996/71319550-398dec80-24e3-11ea-956b-79866a0dbbd0.png)

**Comment by gamtiq** [comment]
Michael,

The new page is really great.
What could be improved on the page (imho):
* Listed projects for each tag should be links pointing to corresponding project's page on _Best of JavaScript_. Also project logos should have tooltips with project names.
* It would be useful to show the last added project for each tag (if it is possible). It would make sort of simple "news of tags".
* I would like to have ability to see all available tags on the page at once (without paging). I suppose some tool (maybe special link near paging links) to achieve this would be helpful.

**Comment by michaelrambeau** [comment]
Thank you very much for your feedback Denis @gamtiq 
It's true that having to click on the pagination buttons when you want to browse the content (whether it's tags or projects) is annoying.
At least the number of tag by page should be increased (20, 30 or even 50 if we show less content by row maybe, to avoid performance problems?)

Or we should get rid of the pagination using:

- "virtualization" (https://bestofjs.org/projects/react-window)
- infinite scrolling (like the homepage of https://www.producthunt.com I like that page by the way, it's a good source of inspiration, I think!)

And you're totally right, we should be able to see the latest projects added (the "newest" ones as they call them on ProductHunt), not only on the tag page, but also on the homepage.

I will work on that, stay tuned!

**Comment by gamtiq** [comment]
> At least the number of tag by page should be increased (20, 30 or even 50 if we show less content by row maybe, to avoid performance problems?)

Considering this I would suggest to add a control (maybe dropdown list) that could be used to select quantity of items per page (10, 20, 30, 50, 100, ...). Sometimes such control can be seen in e-shops catalogs, for example.

> Or we should get rid of the pagination using:
> * "virtualization" (https://bestofjs.org/projects/react-window)
> * infinite scrolling (like the homepage of https://www.producthunt.com I like that page by the way, it's a good source of inspiration, I think!)

I like the idea of "explicit infinite scrolling" (i.e. by using special "Show more" link). Imho "implicit infinite scrolling" (i.e. content is automatically loaded when user scrolls down) is a bit less convenient.

> we should be able to see the latest projects added (the "newest" ones as they call them on ProductHunt), not only on the tag page, but also on the homepage.

Showing "newest" projects on the homepage would be nice.
By the way it would be useful to display on each tag's page the last added project with the corresponding tag (or maybe N last added  projects with such tag).

**Comment by michaelrambeau** [comment]
## Iteration number 2

Thank you Denis and Merry Christmas! @gamtiq 
Let's do the things that are simple first ;)

I've increased the number of elements by page:

- 30 projects by page when you search, pick a tag or go to the "All projects" page
- 20 tags by page in the "All tags" page, each item showing the 5 more popular projects

I've added links and tooltips.

I may handle the "newest" project in a separate request, it requires some time and some deep thinking, you will be involved in the process, if you don't mind 😄 

#### On big screens

![image](https://user-images.githubusercontent.com/5546996/71445439-30a84f80-275d-11ea-9678-dd7712cf3560.png)

#### On small screens

![image](https://user-images.githubusercontent.com/5546996/71445451-4c135a80-275d-11ea-9257-d39d95544bf7.png)

**Comment by gamtiq** [comment]
Merry Christmas, Michael!

The new tags page looks very nice.
I would add tooltips for buttons that open tag's pages.

> I may handle the "newest" project in a separate request

It makes sense.

Thank you for your excellent work!
