### ISSUE TITLE
Adding a `\` in the search bar breaks the website

### ISSUE THREAD

**Issue by abumalick** [bestofjs/bestofjs-webui#85]
Thanks for your work 👍 

Adding a `\` in the search bar breaks the website

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/8377185/75610669-8dd0d080-5b13-11ea-8c39-e69624a0d6f7.png">

**Comment by michaelrambeau** [comment]
Hello Abdullah @abumalick 
Thank you for having reported the problem.
A fix has been released.
Could you reload and try again? (and if possible try any combination that could break the things!)

Example of URL that used to break the site: https://bestofjs.org/projects?query=\&tags=framework

**Comment by michaelrambeau** [comment]
I'm closing the issue but I'm still waiting for your feedback Abdullah @abumalick 
Thank you in advance!

**Comment by abumalick** [comment]
Oh, I thought I answered.
Yes I tested when you pushed the fix and it worked well.

Thank you very much for your work 👍
