### ISSUE TITLE
Add "newest" and "featured" projects added to the top page

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/bestofjs-webui#86]
## Goal 

To make the top page more attractive, instead of showing only the daily rankings (projects sorted "by number of star added yesterday"), it could be interesting to show the latest projects added to _Best of JavaScript_.

## First iteration

A list of the 5 latest additions is added under the dailly rankings.

![image](https://user-images.githubusercontent.com/5546996/76154781-c3824480-6125-11ea-8b3c-6d53222cef35.png)

Clicking on the "View all newest projects" button opens the list of all projects sorted by date of addition.

![image](https://user-images.githubusercontent.com/5546996/76154819-2f64ad00-6126-11ea-9a4b-5d14eb856e89.png)

**Comment by michaelrambeau** [comment]
## Adding a list of _featured projects_

As an attempt to improve the content of the top page, a side bar has been added to show the "Featured projects" (a selection of about 200 projects) in random order.

URL to check: https://next--bestofjs.netlify.com/

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/5546996/76172561-c8550000-61da-11ea-976f-357ebaaa865f.png">

Every 5 seconds, 5 different projects are shown.

I used [react-simple-animate](https://react-simple-animate.now.sh/) from @bluebill1049 to provide a transition effect but the effect could be better, a sliding effect may be nicer. Any feedback from @bluebill1049 would be great!

**Comment by bluebill1049** [comment]
I have to say that I love this new feature! 

I like fade in :) it's subtle.

Maybe give it a try with animate one after another with a little bit of delay `0.05`.

```
{items.map((item, index) => <Animate delay={index * 0.05}) start={{ opacity: 0 }} end={{ opacity: 1}} />}
```

**Comment by michaelrambeau** [comment]
Thank you very much @bluebill1049 it works well!
I've just pushed a new version (this commit https://github.com/bestofjs/bestofjs-webui/commit/dcba1686825ce09862faafcb4110622200a7e99d).

Maybe I should use a place-holder for project icons or find a way to preload them because it can take time to load them.

By the way _React Hook Form_ could be a "featured project" if you provide the project's icon as a **SVG** file.

**Comment by bluebill1049** [comment]
> Maybe I should use a place-holder for project icons or find a way to preload them because it can take time to load them.

Yes sounds like a good idea for user with slow connection and a whole panel with white for awhile is not great user experience.

> By the way React Hook Form could be a "featured project" if you send me the project's icon as a SVG file.

will do! many thanks.

**Comment by bluebill1049** [comment]
here is the logo in SVG: https://github.com/react-hook-form/react-hook-form-website/blob/master/src/images/Logo.svg thanks :)

**Comment by michaelrambeau** [comment]
Hello Bill @bluebill1049 
Thank you, I've uploaded the icon and pushed a new version that uses placeholders while logos are being loaded, could you have a look?
https://next--bestofjs.netlify.com/

Be patient until you see _React Hook Form_ among the "Featured Projects" 😄

**Comment by bluebill1049** [comment]
looks awesome! i have a small suggestion, maybe get the logo size reduced a bit?

**Comment by bluebill1049** [comment]
Minor: maybe the duration should set a bit longer? i flip a bit too fast while my cursor is not on the icons.

**Comment by michaelrambeau** [comment]
@bluebill1049 Thank you Bill for the super fast feedback!
Now the duration of the slide show is 5 seconds, 10 seconds may be better (and later there will be an option to adjust, maybe!)

About the logo size, I wanted to show huge icons in the sidebar to take advantage of the SVG files I use for "featured" projects.
You think that the same size as normal content would be better (50 px instead of 100 px), consistency is better?

**Comment by bluebill1049** [comment]
> You think that the same size as normal content would be better (50 px instead of 100 px), consistency is better? 

I think somewhere between? maybe 80? i try to adjust the logo to see the result but it keep flipping lol.

**Comment by michaelrambeau** [comment]
Hello again Bill @bluebill1049 Could you have a look at the latest changes:

- Smaller icons (80px instead of 100px)
- Slower pace (7s instead of 5)
- Animation effect, from [react-content-loader](https://github.com/danilowoz/react-content-loader)

Just an other idea: I wonder if we should show the "bookmarks projects" the same way, in the top page, because a logged-in user may want to see first the projects he bookmarked rather than a random list of projects.

In your case, if you have bookmarked all your projects on _Best of JavaScript_, you would be able to see all of them (you have 5 projects under your name + React Hook Form!) at a glance.

**Comment by bluebill1049** [comment]
I love those changes (enhancement)!

**Comment by michaelrambeau** [comment]
Thank you for having checked Bill!
Before releasing I have to fix a memory issue, it seems that the number of DOM elements keep increasing (+20,000 after a few minutes) if the window is kept open.

Inspecting https://next--bestofjs.netlify.com/ page with Chrome DevTools Performance monitor

<img width="474" alt="image" src="https://user-images.githubusercontent.com/5546996/76474412-f33f8e00-643e-11ea-832f-c63e16566ed0.png">

Oddly, I can reproduce a similar problem in local but the number of DOM nodes falls when the focus is back on the window, it does not behave the same way as the online version.

**Comment by bluebill1049** [comment]
that's strange. can you try to remove content loader and see if the issue is persist? It's working fine on my mac as well.

**Comment by michaelrambeau** [comment]
i think there is a relation with the content loader, it works better without for both dev and production versions (the result of `npm run build` I mean).

I have to investigate more and find a better strategy, to try to recycle DOM elements maybe, re-using the 5 slots of the slider instead of creating new components every time new projects are shown on the screen, maybe.

**Comment by bluebill1049** [comment]
to be honest i wouldn't even use this third party lib. it's pretty easy to achieve without it.

**Comment by michaelrambeau** [comment]
OK Bill, you're right about the 3rd party lib, all I need is a SVG circle with an animation effect.

Maybe what I did wrong is the preloading feature (to preload the 5 next logos to be displayed on the screen), it seems that by removing this feature, the number of DOM elements keep constant.

I will keep you updated, thank you again for your help!

**Comment by michaelrambeau** [comment]
Hello @bluebill1049 sorry for the delay, could you check the latest version when you have time?
https://next--bestofjs.netlify.com/

I did some changes to try to solve the memory issue.

- Pause the slider when the slider is no more visible on the top page (the `IntersectionObserver` API is used under the hood)
- Pause the slider when the page is no more visible (listening to `visibilitychange` event)
- Different image preloading strategy (using image tags whose visibility is `hidden`)
- No more `react-content-loader` package (but I shamefully stole the SVG generated by the package!)

Thank you in advance!

**Comment by bluebill1049** [comment]
awesome update @michaelrambeau looks great and functions well too.

**Comment by michaelrambeau** [comment]
The latest changes have just been released!

To sum up the changes, three elements have been added to to the homepage to make it more attractive:

- **Newest projects**: the latest projects added to Best of JavaScript
- **Featured Projects**: a selection of important projects, showing randomly on the screen... could you recognize all the logos?
- **Weekly Newsletter**: the latest issue of our newsletter including the rankings by relative growth.

@bluebill1049 Thank you again for your help, is it OK if mention your name in a tweet... to try to promote a bit the new feature?

**Comment by bluebill1049** [comment]
Awesome stuff @michaelrambeau sure, more than happy to retweet too :)

**Comment by gamtiq** [comment]
Hello @michaelrambeau 

New features of the homepage are really fascinating! Thank you! *Best of JS* gets better and better. :-) And goes towards the best service for finding and choosing a project.
Several improvements for consideration:

1. Maybe it is worth to add for each featured project just one associated tag-link (perhaps a tag with maximum number of projects).
2. I suppose it would be useful to have separate page listing all featured projects. In such case it would be possible add "View all featured projects" link below the block. Currently "Featured Projects" is the only block on the homepage without "View..." link.
3. At the moment the homepage displays only "Today Hot Projects". What about to add some switch to show "Hot Projects of Week" and maybe "Hot Projects of Month"? Or maybe to add separate page indicating some statistics about that. Personally I find quite interesting [TIOBE Index](https://www.tiobe.com/tiobe-index/). IMHO something like that but for Front-end projects could make *Best of JS* more attractive.

**Comment by michaelrambeau** [comment]
Thank you for your comments @gamtiq I will do that.

About the point number 3, you can already see the the hot projects of the week, the month and the year if you go to _All Projects_ and click on "Sort" button.

![image](https://user-images.githubusercontent.com/5546996/76911227-a9015580-68f3-11ea-8b7f-bbd186481d64.png)


But i guess it's not obvious, so your idea would be to add a button to be be able to switch the "date range", from the home page, like GitHub does on their [Trending](https://github.com/trending/javascript) page:

![image](https://user-images.githubusercontent.com/5546996/76911160-6d668b80-68f3-11ea-9342-23f8303ef41f.png)

Would it be good if we had such a "Date range" option, from the home page?
By default it would be "Today Hot Projects" but it would be possible to switch to "Last 7 days", "Lasr 30 days" and "Last 12 month".

**Comment by gamtiq** [comment]
> you can already see the the hot projects of the week, the month and the year if you go to All Projects and click on "Sort" button.
> But i guess it's not obvious

Yes, I missed that.

> so your idea would be to add a button to be be able to switch the "date range", from the home page, like GitHub does on their Trending page:
> Would it be good if we had such a "Date range" option, from the home page?
By default it would be "Today Hot Projects" but it would be possible to switch to "Last 7 days", "Lasr 30 days" and "Last 12 month".

Exactly that. I suppose such "Date range" control would be useful.

**Comment by michaelrambeau** [comment]
Thank you again Denis @gamtiq 
If you missed that, it means that everybody missed it, right? 😄 
(because you know the app well!)
So I have to improve that point as soon as possible!

**Comment by michaelrambeau** [comment]
Hello @gamtiq 
I've handled your feedback about the points 1 and 3, adding two elements to the home page here https://next--bestofjs.netlify.com/:

- A button to switch the date range about the _Hot Projects_: Today / This week / This month / This year
- The first tag assigned to the featured projects

Note: clicking on a tag preserve the date range.

Could you check again?
Thank you!

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/5546996/77218934-1e7b5900-6b74-11ea-9552-d3a4fb094363.png">

**Comment by gamtiq** [comment]
Hello @michaelrambeau 
Thank you for your excellent work! New features are great!

> Note: clicking on a tag preserve the date range, for example clicking on the "UI framework" tag while the date range is "this month" opens this page

It's interesting feature but disputable. I suppose it may surprise or even maybe mislead some users because they may miss that the sort order on an opened page is changed from default value (total number of stars). Especially when the feature is expanded on all blocks on the homepage and not only on "Hot Projects" block.
For example, at the moment if you select "This month" on the homepage and then click on "React" tag the first item on the opened page is "React Query" instead of "React" which may surprise some users.
So I would say that the date range switch should only apply for "Hot Projects" block. Moreover perhaps a value selected from the switch should not change links of tags inside the block (I'm not sure about this, but it should be considered).

**Comment by michaelrambeau** [comment]
Thank you very much Denis @gamtiq !
Good points, I'm removing the feature to preserve the date range and I'm fixing the wording.
I'm going to add very soon the "Featured Projects" page you requested.

**Comment by michaelrambeau** [comment]
OK Denis @gamtiq I've just pushed an other version that includes your request number 2: a link to see all "Featured Projects".
Please check again https://next--bestofjs.netlify.com/

![image](https://user-images.githubusercontent.com/5546996/77227183-a63b8480-6bc1-11ea-8c01-321b4c0aca47.png)

TODO: I have styling issues to fix, the spacing between the Hot Project list and the Featured Project list, is not consistent.

**Comment by gamtiq** [comment]
Michael,

The new "Featured Projects" page is cool!
Is it possible to add some description on the page below the title that clarifies what is a "feature project" and/or how the list is composed?

And I suppose it would be useful to add on "All Projects" page the link to "Featured Projects" page. As a result "Featured Projects" page will be more easily accessible.

One more note about "Recently added projects" page (https://next--bestofjs.netlify.com/projects?sort=newest), namely about the corresponding item from "Sort" list. I'm not native English speaker (as you may guess :-) but I think "Sort: Recently added projects first" is not the best wording/combination. As an alternative I may suggest to consider the following variant for the list item: "By date of addition" (or "By time of addition").

**Comment by michaelrambeau** [comment]
Thank you Denis @gamtiq 
What is a featured project? That is a good question!
It may sound weird but a "featured project" is just a project that has a specific SVG icon that shows up instead of the GitHub owner avatar, so it's very arbitrary.
I have spent a lot of time gathering around 200 SVG files during the last months.
I don't know what I should display: "Arbitrary selection of famous projects with a nice logo"?

I didn't use the term "by date of addition" because there is no date of addition displayed anywhere (it's sorted by date but there is no date!) but you're right, I should improve the wording.

I'm not a native English speaker either 😄 so I may ask on the Slack workspace I use to communicate with other people interested in the projects.
By the way could I invite you? (send me your email address but be warned that it's a very quiet Slack workspace!)

**Comment by michaelrambeau** [comment]
Denis, I've just pushed 2 small changes you can see here:

![image](https://user-images.githubusercontent.com/5546996/77251670-03ebd180-6c93-11ea-8ffe-d5c40748f3ea.png)

**Comment by gamtiq** [comment]
Great!
> By the way could I invite you? (send me your email address but be warned that it's a very quiet Slack workspace!)

I doubt that I can make the channel more active. ;-)
You can send the invitation to: idoweb (at) yandex.com

**Comment by michaelrambeau** [comment]
Closing the issue, thank you all, any feedback or suggestion about the homepage is welcome of course!
These changes are part of the [release v0.21](https://github.com/bestofjs/bestofjs-webui/releases/tag/0.21.0)
