### ISSUE TITLE
Improve search UX with a submit button

### ISSUE THREAD

**Issue by davidcetinkaya** [bestofjs/bestofjs-webui#93]
Hello Michael (@michaelrambeau),

I really like the best of JS initiative so thank you for your hard work ⭐️.

One thing I’ve noticed when using the search on my mobile device is that the submit button (with the text return on the screenshot) doesn’t do anything. Maybe it should close the search suggestions and scroll to the results? I’m thinking that this would improve the search UX a bit. What’s your thoughts about this suggestion?

![A55EE4DD-8D6A-4EF6-AA46-27567EAB8F01](https://user-images.githubusercontent.com/11529148/86908134-5fdd4780-c116-11ea-8f61-c8576526259b.png)

Kindly,
David

**Comment by michaelrambeau** [comment]
Hello David @davidcetinkaya 
Thank you for your feedback, long time no see 😄 !
You're right, pushing the enter key does nothing, which is annoying on mobile.
There is no submit button because the search results are filtered while you are typing, so there is no concept of form submission.
It would be better if pushing the return key was closing the keyboard, at least.
I'm going to investigate, starting by checking the example from https://react-select.com/ the library we use for search box.
Meanwhile, if you find anything, let me know!

**Comment by davidcetinkaya** [comment]
Sound like a plan Michael @michaelrambeau. I look forward to the improvement 🙂.

Kindly,
David

**Comment by michaelrambeau** [comment]
Hello David @davidcetinkaya 
Could check the following URL from your mobile: https://bestofjs-git-develop.bestofjs.now.sh/

I did a lazy fix: if the user enters the `Enter` key I remove the focus from the field to close the mobile keyboard.
I hope no other feature is broken.
Thank you for your feedback!

**Comment by davidcetinkaya** [comment]
Hello Michael @michaelrambeau,

Thank you for the fast fix. It’s much better now, the UX feels a lot more intuitive. Appreciate the honesty about your solution 😃.

I have not tried this on any other device other than my mobile phone so I can’t tell if this has any negative implications on other devices, but I don’t think it’s likely.

Cheers!
David

**Comment by michaelrambeau** [comment]
@davidcetinkaya Thank you for having checked David!
I'm working right now to try to implement a kind of timeline showing the most significant projects over the last 10 years.
Mode details here: https://github.com/bestofjs/bestofjs-webui/issues/94
But I'm not sure about what to render on screen, the best way to make it fun... let me know if you are inspired! 😄

**Comment by davidcetinkaya** [comment]
Thank you for your efforts Michael (@michaelrambeau) 🙂. This has been implemented so I’m closing this issue.
