### ISSUE TITLE
Embla Carousel - Add tag to project

### ISSUE THREAD

**Issue by davidjerleke** [bestofjs/bestofjs-webui#96]
Hello Michael @michaelrambeau ,

I’d be happy if you would add the `React` tag to [Embla Carousel](https://github.com/davidcetinkaya/embla-carousel). Like you suggested some time ago, I’ve created a mono repo so the React package is now part of the core package 📦 .

![90AC7613-0B5F-4A56-AB7F-E6CB384CC7B7](https://user-images.githubusercontent.com/11529148/89616756-38021080-d889-11ea-976b-48ae53dbe785.png)

Thank you for your time!
David

**Comment by michaelrambeau** [comment]
Great move David @davidcetinkaya thank you for letting me know!

OK I'm doing that, it will be online in a few hours, when the site data is rebuilt (it happens everyday at 6:00 Japan time if you're curious, 21:00 GMT)

I can see you use a lot your mobile to browse the app, so if you found anything wrong with the layout, let me know.

It also makes me think that I'd like to add offline access to the app.

One last thing, a few days ago I added the ability to click on project's avatar to open the project details page, to increase the "clickable area", let me know if it makes sense... or if the clickable area is still too small on mobiles, thank you!

**Comment by davidcetinkaya** [comment]
Thank you!

Of course, I will let you know if I find more stuff that may need some attention. I need an answer to [this question](https://github.com/bestofjs/bestofjs-webui/issues/94#issuecomment-670352081) when you have a moment.

Cheers!
David

**Comment by michaelrambeau** [comment]
Hello again David @davidcetinkaya 
I was checking your repo and I'm curious about the strategy you followed to set up the mono-repo: it seems you didn't use Lerna and Yarn workspace and there is only one single `package.json`, so it means there is only a single `embla-carousel` package on NPM, if my understanding is correct?
(which is not a problem to me, React packages being only `devDependencies`)

**Comment by davidcetinkaya** [comment]
Hello Michael @michaelrambeau!

Your observation is correct 🙂. It’s a single NPM package where you choose to import which Embla implementation you desire (each implementation is compiled into a separate file with rollup.js), as described in the [docs](https://davidcetinkaya.github.io/embla-carousel/#installation). The alternatives like Lerna and similar felt a bit overkill. At least for now. I might change the approach in the future if I run into issues but right now things are working fine and it feels simple.

You’re right. I should brag about the small bundle size more 😅. Thanks for the idea! And I’m glad you like the cats 🐱. What’s your thoughts about the 3D time pickers at the far bottom?

Thanks Michael!

Best,
David

**Comment by davidcetinkaya** [comment]
Closing this as resolved. Thanks for your help Michael @michaelrambeau! 

![C31FB1AF-2735-46BD-84E4-052F845CD2A4](https://user-images.githubusercontent.com/11529148/89702154-26c70b80-d93e-11ea-8452-f398f93dea8a.jpeg)

Best
David

**Comment by michaelrambeau** [comment]
Hello David @davidcetinkaya 
It's your day of glory, you are number 2, congratulations! 🎉 
I'm curious about what happened, did you promote _Embla_ on some media?

![image](https://user-images.githubusercontent.com/5546996/90448964-630a2100-e121-11ea-9e84-bdd5c084c657.png)

**Comment by davidcetinkaya** [comment]
Hello Michael @michaelrambeau,

Thanks for sharing this! Yes, after rebuilding the documentation and releasing v.3, I decided to [share it on reddit](https://www.reddit.com/r/javascript/comments/ib9pw3/embla_carousel_the_most_fluid_carousel_library). It seems like people appreciate it 😊.

Cheers!
David

**Comment by michaelrambeau** [comment]
That's cool David! @davidcetinkaya 
By the way, I can see badge on your README.md... did you know we provide badge too?
Like the one here: https://github.com/tannerlinsley/react-query
We provide different variations (daily, weekly, monthly numbers)
But you may think that it adds to much clutter to your README.md so you can refuse this offer, no problem!

**Comment by davidcetinkaya** [comment]
Thank you Michael! @michaelrambeau 

Yes I've checked those badges out and they look awesome. At the time of writing Embla Carousel isn't gaining many ⭐ per day (excluding the peak right now caused by the reddit post) so maybe it could have a negative impact on visitors, I don't know. But if people start sharing it more and it gets more traction over time, I'll definitely add a badge.

Thanks Michael 🙂.

**Comment by davidcetinkaya** [comment]
Hello Michael (@michaelrambeau),

That's cool, didn't even know javascript weekly mentioned it. Thanks a lot 🙂. The newsletter suggestion is great, go with that. Appreciate it a lot Michael.

Have a great day and thanks a lot. We'll probably be in touch soon again 🙂.
David

**Comment by davidjerleke** [comment]
Hi @michaelrambeau,

I hope you're doing great 🙂?
Would you consider adding the following tags to [Embla Carousel](https://bestofjs.org/projects/embla-carousel)? 

- React
- Vue
- Svelte



Because Embla Carousel now supports all of these libraries/frameworks and has wrappers for them. All wrappers are part of the same monorepo. 

PS. For whatever reason the `React` tag was added [way back](https://github.com/bestofjs/bestofjs-webui/issues/96#issuecomment-670820866) but seem to have disappeared.

Thank you for your time!

Best,
David

**Comment by michaelrambeau** [comment]
Hello David @davidjerleke I'm fine, it's good to see you!

Sorry for the miss about the tags, I'm fixing, it will be online in 24 hours.

I've just noticed Embla is the trendiest slider of the week on _Best of JS_, it's impressive!

**Comment by davidjerleke** [comment]
Thank you very much for the help @michaelrambeau ⭐. I'm closing this as resolved:

<img width="595" alt="tags" src="https://user-images.githubusercontent.com/11529148/184084551-4e5e3a79-bf57-4892-8954-cd6bc39d3dac.png">

### On a side note
Is this how you prefer to add tags? That is, creating an issue in this repository? Because I browsed [bestofjs](https://bestofjs.org/) for a while looking for information about how to request new tags and didn't find anything. It could just be me getting old though so if that's the case, you can ignore this side note 😉.

**Comment by michaelrambeau** [comment]
Thank you for having checked David @davidjerleke 
You are 100% right, there is no "official" way to suggest corrections about tags, so contacting us via GitHub is fine.
Or you can join the Discord server where we are supposed to discuss with the other members, you'd be welcome!
(it's a very quiet place actually!)
I should add a note on the top page.
And I guarantee you are not getting old... at least not as much as me 😄 

Sharing the screenshot to celebrate your success (number 2 over the last 12 months)

![image](https://user-images.githubusercontent.com/5546996/184090200-d11b38f5-6fab-4a55-8684-32de2b137258.png)

**Comment by davidjerleke** [comment]
Thank you for your swift response.
I like your "time to celebrate" initiatives, it's very encouraging 🙂.

> Or you can join the Discord server where we are supposed to discuss with the other members, you'd be welcome!

Thanks! I'll make sure to join your Discord when I have some input, feedback, or questions next time.

Cheers,
David
